name: flutterlabbatrakov
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - images/
  fonts:
  - family: SfProText
    fonts:
    - asset: fonts/SFProText-Regular.ttf
    - asset: fonts/SFProText-Medium.ttf
  - family:  MyFlutterApp
    fonts:
    - asset: fonts/MyFlutterApp.ttf
